### ISSUE TITLE
[Proto] Implement a State result type

### ISSUE THREAD

**Issue by Roland-djee** [pasqal-io/qadence2-core#6]
To allow the handling of:

- [ ] State vectors
- [ ] Density matrices useful for https://github.com/pasqal-io/qadence/issues/367
- [ ] Samples ?

Unfinished prototype [here](https://github.com/pasqal-io/qadence/pull/377)

(issue transferred since core is more suitable to address it)

**Comment by Roland-djee** [comment]
@kaosmicadei @Doomsk Is this still necessary ? I think it'll be handle by the runtime.

**Comment by Doomsk** [comment]
> @kaosmicadei @Doomsk Is this still necessary ? I think it'll be handle by the runtime.

@Roland-djee indeed. It's mostly likely to be handled in the platforms

**Comment by Roland-djee** [comment]
@Doomsk Is it tracked somewhere ? Can I close this one ?

**Comment by Roland-djee** [comment]
Closing as tracked elsewhere.
